### ISSUE TITLE
Compatibility with PostCSS 8

### ISSUE THREAD

**Issue by Semigradsky** [shrpne/postcss-page-break#5]
**Thanks for your PostCSS plugin!**

As you probably know, PostCSS 8 was released a few days ago. It would be great if you could make this plugin compatible with the latest version. The creators of the project have even released this [migration guide](https://evilmartians.com/chronicles/postcss-8-plugin-migration).

**Comment by shrpne** [comment]
Done https://github.com/shrpne/postcss-page-break/commit/5074a0059fdafaf9b629601803837f7afe1c8232

Published under v3.0.0
